from __future__ import annotations

import os
import threading
from http import HTTPStatus
from http.server import ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

from .chat_gateway import SESSION_TTL_SECONDS, SessionStore, TelegramBridge, _lan_hint, _parse_allowed_ids
from .chat_gateway_v2 import ProgressApplication, ProgressChatService, ProgressHTTPHandler
from .config import load_config
from .human_report import create_human_report
from .models import TaskStatus
from .orchestrator import Orchestrator
from .privacy import redact_sensitive_text


class HumanReportChatService(ProgressChatService):
    """3Agent chat service that returns a task-scoped reader report.

    The full daily report and audit artifacts are still generated by WorkflowRunner,
    but they are not pasted into the main chat answer.
    """

    def _execute(self, job_id: str) -> None:
        job = self.get(job_id)
        if job is None:
            return
        self._update(job_id, status="running")
        task = self.orchestrator.store.create_task(job.message[:96], job.message)
        self._update(job_id, task_id=task.task_id)
        self._stage(job_id, "research", "running", "Agent 1 is researching and validating sources.")
        stop = threading.Event()
        monitor = threading.Thread(
            target=self._monitor,
            args=(job_id, task.task_id, stop),
            name=f"3agent-stage-{job_id}",
            daemon=True,
        )
        monitor.start()
        try:
            result = self.orchestrator.workflow.run_task(
                task.task_id,
                live=True,
                audience="R&D internal",
                purpose="answer the user request with evidence",
                language=job.language,
                slide_count=6,
                output_format=job.output_format,
            )
            handoff = next(
                (item for item in result.research_artifacts if item.endswith("_handoff.json")),
                "",
            )

            report_paths: list[str] = []
            answer = ""
            report_warnings: list[str] = []
            if handoff:
                bundle = create_human_report(
                    task_id=task.task_id,
                    title=task.title,
                    request=task.request,
                    handoff_path=handoff,
                    artifact_root=self.orchestrator.artifacts.root,
                    language=job.language,
                )
                answer = bundle.markdown
                report_paths = list(bundle.paths)
                report_warnings = list(bundle.warnings)
                for path in report_paths:
                    suffix = Path(path).suffix.lower().lstrip(".") or "file"
                    self.orchestrator.store.record_artifact(
                        task.task_id,
                        "daily_report",
                        f"human_report_{suffix}",
                        path,
                    )
                self.orchestrator.store.record_activity(
                    task.task_id,
                    "daily_report",
                    "human_report_created",
                    "ok" if not report_warnings else "warning",
                    "outputs=" + ",".join(Path(x).suffix.lstrip(".") for x in report_paths),
                )
            else:
                answer = (
                    "# 3Agent Report\n\n"
                    "The workflow did not produce a validated research handoff, so a reader-facing "
                    "report could not be generated without inventing content.\n"
                )

            if report_warnings:
                answer += "\n\n> " + " | ".join(report_warnings)

            artifacts = list(dict.fromkeys(
                report_paths
                + list(result.presentation_artifacts)
                + list(result.research_artifacts)
                + list(result.daily_report_artifacts)
            ))
            status = "completed" if result.status == "completed" else result.status
            if status == "completed":
                self._stage(job_id, "research", "completed")
                self._stage(job_id, "presentation", "completed")
                self._stage(job_id, "daily_report", "completed", "Reader report and audit log are ready.")
            elif status == "blocked":
                self._stage(job_id, "research", "blocked")
                self._stage(job_id, "presentation", "skipped")
                self._stage(job_id, "daily_report", "completed", "Blocker report recorded.")
            elif status == "failed":
                current = self.orchestrator.store.get_task(task.task_id)
                if current.status == TaskStatus.FAILED:
                    running_presentation = any(
                        stage["id"] == "presentation" and stage["status"] == "running"
                        for stage in self._jobs[job_id].stages
                    )
                    if running_presentation:
                        self._stage(job_id, "presentation", "failed")
                self._stage(job_id, "daily_report", "completed", "Failure evidence recorded.")

            self._update(
                job_id,
                status=status,
                answer=answer,
                error=redact_sensitive_text(result.error) if result.error else None,
                artifacts=artifacts,
            )
        except Exception as exc:
            self._stage(job_id, "daily_report", "failed")
            self._update(
                job_id,
                status="failed",
                error=redact_sensitive_text(f"{type(exc).__name__}: {exc}")[:1200],
            )
        finally:
            stop.set()
            monitor.join(timeout=1)


HTML_V3 = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>3Agent</title>
<style>
:root{color-scheme:dark;--bg:#101113;--panel:#17191d;--line:#2a2d33;--text:#eceef2;--muted:#9aa0aa;--accent:#d7ff6e;--danger:#ff8e8e;--ok:#8be28b;--warn:#ffd36e}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.58 system-ui,-apple-system,Segoe UI,sans-serif;height:100vh}.shell{max-width:1080px;margin:auto;height:100vh;display:flex;flex-direction:column}.top{padding:18px 22px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:12px}.brand{font-weight:700;font-size:18px}.dot{width:9px;height:9px;border-radius:50%;background:var(--accent)}.sub{color:var(--muted);font-size:12px;margin-left:auto}#messages{flex:1;overflow:auto;padding:28px 18px 180px}.msg{max-width:900px;margin:0 auto 24px;word-break:break-word}.who{font-size:12px;color:var(--muted);margin-bottom:6px}.bubble{padding:18px 20px;border:1px solid var(--line);border-radius:16px;background:var(--panel)}.user .bubble{background:#202329;white-space:pre-wrap}.error{color:var(--danger)}.report h1{font-size:25px;margin:0 0 14px}.report h2{font-size:17px;margin:22px 0 8px}.report p{margin:7px 0}.report ul{margin:6px 0 8px;padding-left:22px}.report li{margin:5px 0}.report blockquote{margin:10px 0;padding:9px 12px;border-left:3px solid var(--accent);background:#1e211d;color:#dfe8c4}.report hr{border:0;border-top:1px solid var(--line);margin:20px 0}.stages{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:10px}.stage{border:1px solid var(--line);border-radius:12px;padding:9px 10px;font-size:12px}.stage b{display:block}.stage small{color:var(--muted)}.stage.completed{border-color:#3e7048}.stage.running{border-color:#75883a}.stage.blocked,.stage.failed{border-color:#8d4c4c}.stage.skipped{opacity:.55}.answerTools{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.answerTools button,.downloads a{color:var(--text);text-decoration:none;border:1px solid var(--line);background:#24272d;border-radius:9px;padding:6px 10px;font-size:12px}.downloads{display:flex;gap:8px;flex-wrap:wrap}.downloads a.primaryFile{color:#14170d;background:var(--accent);border-color:var(--accent);font-weight:700}.tech{margin-top:10px;border:1px solid var(--line);border-radius:10px;padding:8px 10px;color:var(--muted)}.tech summary{cursor:pointer}.tech a{display:inline-block;color:var(--accent);text-decoration:none;margin:6px 8px 2px 0;font-size:12px}.composer{position:fixed;left:0;right:0;bottom:0;padding:12px 18px 22px;background:linear-gradient(transparent,var(--bg) 25%)}.box{max-width:940px;margin:auto;background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:10px}.row{display:flex;gap:8px;align-items:flex-end}textarea{flex:1;resize:none;min-height:52px;max-height:160px;background:transparent;border:0;outline:0;color:var(--text);padding:10px;font:inherit}button,select,input{background:#252830;color:var(--text);border:1px solid #343842;border-radius:10px;padding:9px 12px}button{cursor:pointer}button.primary{background:var(--accent);color:#151712;border-color:var(--accent);font-weight:700}.tools{display:flex;gap:8px;padding:0 8px 4px;align-items:center}.hint{color:var(--muted);font-size:11px;margin-left:auto}#login{position:fixed;inset:0;background:rgba(10,11,13,.96);z-index:5;display:flex;align-items:center;justify-content:center}.card{width:min(420px,90vw);background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:24px}.card input{width:100%;margin:8px 0 12px}.hidden{display:none!important}@media(max-width:700px){.stages{grid-template-columns:1fr}.sub{display:none}.hint{display:none}.tools{flex-wrap:wrap}}
</style></head><body>
<div id="login"><div class="card"><h2>3Agent LAN</h2><p style="color:var(--muted)">Enter the server access key.</p><input id="key" type="password" placeholder="Access key"><button class="primary" onclick="login()">Connect</button><p id="loginErr" class="error"></p></div></div>
<div class="shell"><div class="top"><span class="dot"></span><span class="brand">3Agent</span><span class="sub">Research → Presentation → Human Report</span></div><div id="messages"></div></div>
<div class="composer"><div class="box"><div class="tools"><select id="lang"><option value="ja">日本語</option><option value="vi">Tiếng Việt</option><option value="en">English</option></select><select id="fmt"><option value="source">Report</option><option value="pptx">Report + PPTX</option><option value="pdf">Report + Slide PDF</option><option value="all">Report + PPTX + Slide PDF</option></select><span class="hint">Every completed task includes DOCX/PDF reader report</span></div><div class="row"><textarea id="input" placeholder="Ask 3Agent..."></textarea><button class="primary" onclick="sendMsg()">Send</button></div></div></div>
<script>
const messages=document.getElementById('messages'),input=document.getElementById('input');
function renderStages(stages){const wrap=document.createElement('div');wrap.className='stages';for(const s of stages||[]){const e=document.createElement('div');e.className='stage '+s.status;e.innerHTML='<b></b><small></small>';e.children[0].textContent=s.label+' · '+s.status;e.children[1].textContent=s.detail||'';wrap.appendChild(e)}return wrap}
function appendInline(el,text){const re=/(https?:\/\/[^\s]+)/g;let pos=0;for(const m of text.matchAll(re)){el.appendChild(document.createTextNode(text.slice(pos,m.index)));const a=document.createElement('a');a.href=m[0];a.target='_blank';a.rel='noopener noreferrer';a.textContent=m[0];a.style.color='var(--accent)';el.appendChild(a);pos=m.index+m[0].length}el.appendChild(document.createTextNode(text.slice(pos)))}
function renderReport(text){const root=document.createElement('div');root.className='report';let list=null;for(const raw of String(text||'').split('\n')){const line=raw.trimEnd();if(!line.trim()){list=null;continue}if(line==='---'){root.appendChild(document.createElement('hr'));list=null;continue}const h=line.match(/^(#{1,2})\s+(.*)$/);if(h){const el=document.createElement(h[1].length===1?'h1':'h2');appendInline(el,h[2].replace(/\*\*/g,''));root.appendChild(el);list=null;continue}if(line.startsWith('> ')){const q=document.createElement('blockquote');appendInline(q,line.slice(2).replace(/\*\*/g,''));root.appendChild(q);list=null;continue}if(line.startsWith('- ')){if(!list){list=document.createElement('ul');root.appendChild(list)}const li=document.createElement('li');appendInline(li,line.slice(2).replace(/\*\*/g,''));list.appendChild(li);continue}const p=document.createElement('p');appendInline(p,line.replace(/\*\*/g,'').replace(/`/g,''));root.appendChild(p);list=null}return root}
function isPrimary(a){return /_report\.(docx|pdf|md)$/i.test(a.name)||/\.pptx$/i.test(a.name)}
function renderArtifacts(items){const wrap=document.createElement('div');const primary=document.createElement('div');primary.className='downloads';const tech=document.createElement('details');tech.className='tech';const sum=document.createElement('summary');sum.textContent='Technical evidence / 監査用データ';tech.appendChild(sum);let techCount=0;for(const a of items||[]){const x=document.createElement('a');x.href=a.url;x.textContent='↓ '+a.name;if(isPrimary(a)){if(/_report\.(docx|pdf)$/i.test(a.name))x.className='primaryFile';primary.appendChild(x)}else{tech.appendChild(x);techCount++}}if(primary.children.length)wrap.appendChild(primary);if(techCount)wrap.appendChild(tech);return wrap}
async function copyAnswer(node){const text=node.dataset.answer||'';try{await navigator.clipboard.writeText(text)}catch(e){const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}const b=node.querySelector('.copyBtn');if(b){const old=b.textContent;b.textContent='Copied ✓';setTimeout(()=>b.textContent=old,1200)}}
function renderActions(node,job){const old=node.querySelector('.answerTools');if(old)old.remove();if(!job||!job.answer)return;const bar=document.createElement('div');bar.className='answerTools';const b=document.createElement('button');b.className='copyBtn';b.textContent='Copy answer';b.onclick=()=>copyAnswer(node);bar.appendChild(b);node.insertBefore(bar,node.querySelector('.bubble').nextSibling)}
function add(who,text,cls='',job=null){const d=document.createElement('div');d.className='msg '+cls;const h=document.createElement('div');h.className='who';h.textContent=who;d.appendChild(h);if(job)d.appendChild(renderStages(job.stages));const b=document.createElement('div');b.className='bubble';if(cls.includes('user'))b.textContent=text;else b.appendChild(renderReport(text));d.appendChild(b);d.dataset.answer=job&&job.answer?job.answer:text;if(job){renderActions(d,job);if(job.artifacts)d.appendChild(renderArtifacts(job.artifacts))}messages.appendChild(d);messages.scrollTop=messages.scrollHeight;return d}
function updateNode(node,j){const old=node.querySelector('.stages');if(old)old.remove();node.insertBefore(renderStages(j.stages),node.querySelector('.bubble'));const text=(j.status==='queued'||j.status==='running')?'Processing through 3 agents…':(j.answer||(j.error||j.status));const b=node.querySelector('.bubble');b.innerHTML='';b.appendChild(renderReport(text));node.dataset.answer=j.answer||'';renderActions(node,j);const oldA=node.querySelector('.downloads')?.parentElement;if(oldA&&oldA!==node.querySelector('.bubble'))oldA.remove();const oldTech=node.querySelector('.tech');if(oldTech)oldTech.remove();if(j.artifacts&&j.artifacts.length)node.appendChild(renderArtifacts(j.artifacts));if(j.status==='failed'&&!j.answer)node.classList.add('error')}
async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});if(r.status===401){document.getElementById('login').classList.remove('hidden');throw new Error('Authentication required')}const data=await r.json();if(!r.ok)throw new Error(data.error||r.statusText);return data}
async function login(){const key=document.getElementById('key').value;try{await api('/api/login',{method:'POST',body:JSON.stringify({token:key})});document.getElementById('login').classList.add('hidden');document.getElementById('loginErr').textContent='';await loadRecent()}catch(e){document.getElementById('loginErr').textContent=e.message}}
async function loadRecent(){try{const d=await api('/api/recent');messages.innerHTML='';for(const j of d.jobs.reverse()){add('You',j.message,'user');add('3Agent',j.answer||(j.error||'['+j.status+']'),j.status==='failed'&&!j.answer?'error':'',j)}}catch(e){}}
async function sendMsg(){const text=input.value.trim();if(!text)return;const fmt=document.getElementById('fmt').value,lang=document.getElementById('lang').value;input.value='';add('You',text,'user');const pending=add('3Agent','Queued…','',{answer:'',stages:[{label:'Agent 1 · Research',status:'queued'},{label:'Agent 2 · Presentation',status:'queued'},{label:'Agent 3 · Human Report',status:'queued'}],artifacts:[]});try{const d=await api('/api/chat',{method:'POST',body:JSON.stringify({message:text,language:lang,format:fmt})});updateNode(pending,d);poll(d.job_id,pending)}catch(e){pending.querySelector('.bubble').textContent=e.message;pending.classList.add('error')}}
async function poll(id,node){try{const j=await api('/api/jobs/'+id);updateNode(node,j);if(j.status==='queued'||j.status==='running')setTimeout(()=>poll(id,node),1200)}catch(e){node.querySelector('.bubble').textContent=e.message;node.classList.add('error')}}
input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMsg()}});(async()=>{try{await api('/api/recent');document.getElementById('login').classList.add('hidden');await loadRecent()}catch(e){}})();
</script></body></html>'''


class HumanReportHTTPHandler(ProgressHTTPHandler):
    server_version = "3AgentChat/0.3"

    def do_GET(self) -> None:
        path = urlparse(self.path).path
        if path == "/":
            if not self._private_or_reject():
                return
            body = HTML_V3.encode("utf-8")
            self.send_response(HTTPStatus.OK)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)
            return
        super().do_GET()


def main() -> int:
    config = load_config()
    orchestrator = Orchestrator(config)
    orchestrator.initialize()
    (config.artifact_root / "reports").mkdir(parents=True, exist_ok=True)
    access_token = os.getenv("THREE_AGENT_WEB_ACCESS_TOKEN", "")
    host = os.getenv("THREE_AGENT_WEB_HOST", "0.0.0.0")
    port = int(os.getenv("THREE_AGENT_WEB_PORT", "8787"))
    language = os.getenv("THREE_AGENT_CHAT_LANGUAGE", "ja")
    service = HumanReportChatService(orchestrator, default_language=language)
    service.start()
    sessions = SessionStore(access_token)
    app = ProgressApplication(service, sessions, config.artifact_root)
    telegram_token = os.getenv("THREE_AGENT_TELEGRAM_BOT_TOKEN", "").strip()
    allowed_ids = _parse_allowed_ids(os.getenv("THREE_AGENT_TELEGRAM_ALLOWED_USER_IDS", ""))
    if telegram_token:
        bridge = TelegramBridge(service, orchestrator.internet_gateway, telegram_token, allowed_ids)
        threading.Thread(target=bridge.run_forever, name="3agent-telegram", daemon=True).start()
        print(f"[3Agent-Chat] Telegram enabled; authorized users={len(allowed_ids)}.", flush=True)
    else:
        print("[3Agent-Chat] Telegram disabled (no bot token configured).", flush=True)
    httpd = ThreadingHTTPServer((host, port), HumanReportHTTPHandler)
    httpd.app = app  # type: ignore[attr-defined]
    print(f"[3Agent-Chat] LAN UI: {_lan_hint(host, port)}", flush=True)
    print("[3Agent-Chat] Reader report + Copy + DOCX/PDF export enabled.", flush=True)
    try:
        httpd.serve_forever(poll_interval=0.5)
    except KeyboardInterrupt:
        pass
    finally:
        httpd.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
