from __future__ import annotations

PART_6 = r"""function renderHistoryList(){const pinned=document.getElementById('pinnedList'),history=document.getElementById('historyList');pinned.innerHTML='';history.innerHTML='';const p=state.conversations.filter(x=>x.pinned),normal=state.conversations.filter(x=>!x.pinned);document.getElementById('pinnedSection').classList.toggle('hidden',p.length===0);document.getElementById('historyHeading').textContent=state.searchQuery?'Search results':'Chats';const build=(item)=>{const row=document.createElement('div');row.className='conversation-row'+(item.conversation_id===state.currentConversationId?' active':'');row.dataset.id=item.conversation_id;const icon=document.createElement('span');icon.className='conversation-icon';icon.innerHTML=svgChat();const title=document.createElement('span');title.className='conversation-title';title.textContent=item.title;title.title=item.title;const pin=document.createElement('button');pin.type='button';pin.className='pin-btn'+(item.pinned?' pinned':'');pin.title=item.pinned?'Unpin':'Pin';pin.setAttribute('aria-label',pin.title);pin.innerHTML='<svg viewBox="0 0 24 24"><path d="m9 3 6 0 1 5 3 3-6 1v7l-1 2-1-2v-7l-6-1 3-3z"/></svg>';pin.onclick=(e)=>{e.stopPropagation();setPinned(item.conversation_id,!item.pinned)};row.append(icon,title,pin);row.onclick=()=>openConversation(item.conversation_id);return row};for(const item of p)pinned.appendChild(build(item));for(const item of normal)history.appendChild(build(item));if(!p.length&&!normal.length){const e=document.createElement('div');e.className='history-empty';e.textContent=state.searchQuery?'No matching chats':'No saved chats yet';history.appendChild(e)}}
async function loadConversations(query=state.searchQuery){state.searchQuery=String(query||'').trim();const d=await api('/api/conversations'+(state.searchQuery?'?q='+encodeURIComponent(state.searchQuery):''));state.conversations=d.conversations||[];renderHistoryList()}
async function openConversation(id){const d=await api('/api/conversations/'+encodeURIComponent(id));state.currentConversationId=d.conversation_id;localStorage.setItem('workspace.currentConversationId',d.conversation_id);document.getElementById('conversationName').textContent=d.title||'Chat';messages.innerHTML='';for(const m of d.messages||[]){if(m.role==='user')addMessage('You',m.content,'user');else addMessage('WorkSpace',m.content,m.status==='failed'?'error':'')}if(!(d.messages||[]).length)showEmpty();renderHistoryList();if(window.innerWidth<=760)setSidebarCollapsed(true)}
function newChat(){state.currentConversationId=null;localStorage.removeItem('workspace.currentConversationId');document.getElementById('conversationName').textContent='New chat';messages.innerHTML='';showEmpty();renderHistoryList();input.focus();if(window.innerWidth<=760)setSidebarCollapsed(true)}
async function setPinned(id,pinned){try{await api('/api/conversations/'+encodeURIComponent(id)+'/pin',{method:'POST',body:JSON.stringify({pinned:!!pinned})});await loadConversations()}catch(e){showToast(e.message)}}
function openSearch(){if(state.sidebarCollapsed)setSidebarCollapsed(false);const box=document.getElementById('historySearchBox');box.classList.remove('hidden');setTimeout(()=>document.getElementById('historySearchInput').focus(),40)}
function closeSearch(){state.searchQuery='';const inputEl=document.getElementById('historySearchInput');inputEl.value='';document.getElementById('historySearchBox').classList.add('hidden');loadConversations('').catch(()=>{})}

function cap(name){return state.capabilities&&state.capabilities.features&&state.capabilities.features[name]?state.capabilities.features[name]:{enabled:false,state_label:'Unavailable',reason:'Capability unavailable'}}
function syncCapabilities(){for(const row of document.querySelectorAll('.menu-row[data-action]')){const name=row.dataset.action,feature=name==='upload'?cap('upload'):name==='library'?cap('library'):cap(name);row.classList.toggle('disabled',!feature.enabled);row.setAttribute('aria-disabled',feature.enabled?'false':'true');const label=row.querySelector('.menu-state');if(label)label.textContent=feature.state_label||''}const mic=cap('voice_input');document.getElementById('micBtn').setAttribute('aria-disabled',mic.enabled?'false':'true')}
async function loadCapabilities(){state.capabilities=await api('/api/capabilities');syncCapabilities()}
async function loadSession(){const d=await api('/api/session');state.session=d;document.getElementById('accountName').textContent=d.display_name||'WorkSpace User';document.getElementById('accountSub').textContent=d.subtitle||'Local LAN session';document.getElementById('accountAvatar').textContent=d.initials||'W'}
function setMode(mode){if(mode!=='chat'){const f=cap(mode);if(!f.enabled){showToast(f.reason||'This capability is unavailable');return}}state.requestMode=mode;const pill=document.getElementById('modePill'),label=document.getElementById('modeLabel');if(mode==='chat'){pill.classList.remove('visible');label.textContent=''}else{label.textContent=mode==='web_search'?'Web search':'Deep research';pill.classList.add('visible')}document.getElementById('plusMenu').classList.remove('open')}
function renderAttachments(){const wrap=document.getElementById('attachments');wrap.innerHTML='';for(let i=0;i<state.selectedFiles.length;i++){const f=state.selectedFiles[i],c=document.createElement('div');c.className='chip';const s=document.createElement('span');s.textContent=f.name;const b=document.createElement('button');b.type='button';b.textContent='×';b.onclick=()=>{state.selectedFiles.splice(i,1);renderAttachments()};c.append(s,b);wrap.appendChild(c)}for(const [id,item] of state.selectedLibrary){const c=document.createElement('div');c.className='chip';const s=document.createElement('span');s.textContent=item.name;const b=document.createElement('button');b.type='button';b.textContent='×';b.onclick=()=>{state.selectedLibrary.delete(id);renderAttachments()};c.append(s,b);wrap.appendChild(c)}}
function fileBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const v=String(r.result||'');resolve(v.includes(',')?v.split(',',2)[1]:v)};r.onerror=()=>reject(r.error||new Error('File read failed'));r.readAsDataURL(file)})}
"""
