from __future__ import annotations

PART_7 = r"""async function uploadOne(file){const max=state.capabilities?.limits?.max_upload_bytes||16*1024*1024;if(file.size>max)throw new Error(file.name+': file exceeds '+Math.ceil(max/1024/1024)+' MiB');const data=await fileBase64(file);return api('/api/upload',{method:'POST',body:JSON.stringify({name:file.name,type:file.type||'',data_base64:data})})}
async function openLibrary(){if(!cap('library').enabled){showToast(cap('library').reason);return}const d=await api('/api/uploads'),list=document.getElementById('libraryList');list.innerHTML='';if(!(d.uploads||[]).length){const e=document.createElement('div');e.className='library-empty';e.textContent='No validated uploads for this LAN session yet.';list.appendChild(e)}for(const item of d.uploads||[]){const row=document.createElement('label');row.className='library-item';const ck=document.createElement('input');ck.type='checkbox';ck.dataset.id=item.upload_id;ck.checked=state.selectedLibrary.has(item.upload_id);const body=document.createElement('div'),name=document.createElement('div'),meta=document.createElement('div');name.className='library-name';name.textContent=item.name;meta.className='library-meta';meta.textContent=item.kind+' · '+Math.ceil(item.size/1024)+' KB';body.append(name,meta);const stateEl=document.createElement('span');stateEl.className='menu-state';stateEl.textContent=item.document_count+' docs · '+item.image_count+' images';row.append(ck,body,stateEl);row.dataset.payload=JSON.stringify(item);list.appendChild(row)}document.getElementById('libraryModal').classList.add('open');document.getElementById('plusMenu').classList.remove('open')}
function applyLibrary(){for(const row of document.querySelectorAll('.library-item')){const ck=row.querySelector('input');if(!ck)continue;const item=JSON.parse(row.dataset.payload);if(ck.checked)state.selectedLibrary.set(item.upload_id,item);else state.selectedLibrary.delete(item.upload_id)}renderAttachments();document.getElementById('libraryModal').classList.remove('open')}
function unavailable(name){const f=cap(name);showToast(f.reason||'This feature is not available')}

async function sendMsg(){const text=input.value.trim();if(!text)return;document.getElementById('sendBtn').disabled=true;const files=state.selectedFiles.slice(),libraryIds=Array.from(state.selectedLibrary.keys()),names=[...files.map(f=>f.name),...Array.from(state.selectedLibrary.values()).map(x=>x.name)];input.value='';state.selectedFiles=[];state.selectedLibrary.clear();renderAttachments();addMessage('You',text+(names.length?'\n\nAttached: '+names.join(', '):''),'user');const pending=addMessage('WorkSpace',files.length?'Uploading and validating files…':'Queued…','',{answer:'',stages:[{label:'Research',status:'queued'},{label:'Presentation',status:'queued'},{label:'Human Report',status:'queued'}],artifacts:[]});try{const uploadIds=libraryIds.slice();for(let i=0;i<files.length;i++){pending.querySelector('.bubble').textContent='Uploading '+(i+1)+'/'+files.length+': '+files[i].name;const result=await uploadOne(files[i]);uploadIds.push(result.upload_id)}const d=await api('/api/chat',{method:'POST',body:JSON.stringify({message:text,language:document.getElementById('lang').value,format:document.getElementById('fmt').value,upload_ids:uploadIds,mode:state.requestMode,effort:document.getElementById('effort').value,conversation_id:state.currentConversationId})});state.currentConversationId=d.conversation_id;localStorage.setItem('workspace.currentConversationId',d.conversation_id);document.getElementById('conversationName').textContent=text.replace(/\s+/g,' ').slice(0,96);updateNode(pending,d);await loadConversations();poll(d.job_id,pending,d.conversation_id)}catch(e){pending.querySelector('.bubble').textContent=e.message;pending.classList.add('error')}finally{document.getElementById('sendBtn').disabled=false}}
async function poll(id,node,conversationId){try{const j=await api('/api/jobs/'+id);if(j.status==='queued'||j.status==='running'){if(node.isConnected)updateNode(node,j);setTimeout(()=>poll(id,node,conversationId),1800);return}if(node.isConnected)updateNode(node,j);await loadConversations();if(state.currentConversationId===conversationId&&!node.isConnected)await openConversation(conversationId)}catch(e){if(node.isConnected){node.querySelector('.bubble').textContent=e.message;node.classList.add('error')}}}

async function login(){const key=document.getElementById('key').value;try{await api('/api/login',{method:'POST',body:JSON.stringify({token:key})});document.getElementById('login').classList.add('hidden');document.getElementById('loginErr').textContent='';await initializeWorkspace()}catch(e){document.getElementById('loginErr').textContent=e.message}}
async function logout(){try{await api('/api/logout',{method:'POST',body:JSON.stringify({})})}catch(e){}state.currentConversationId=null;state.conversations=[];document.getElementById('accountMenu').classList.remove('open');document.getElementById('login').classList.remove('hidden');document.getElementById('key').value='';showEmpty()}
async function initializeWorkspace(){await Promise.all([loadCapabilities(),loadSession(),loadConversations('')]);const remembered=localStorage.getItem('workspace.currentConversationId');if(remembered&&state.conversations.some(x=>x.conversation_id===remembered)){try{await openConversation(remembered);return}catch(e){}}newChat()}

document.getElementById('sidebarToggle').onclick=toggleSidebar;
document.getElementById('mobileMenuBtn').onclick=()=>setSidebarCollapsed(false);
document.getElementById('newChatBtn').onclick=newChat;
document.getElementById('historySearchBtn').onclick=openSearch;
document.getElementById('clearHistorySearch').onclick=closeSearch;
document.getElementById('historySearchInput').addEventListener('input',e=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>loadConversations(e.target.value).catch(err=>showToast(err.message)),180)});
document.getElementById('accountBtn').onclick=()=>document.getElementById('accountMenu').classList.toggle('open');
document.getElementById('logoutBtn').onclick=logout;
document.getElementById('loginBtn').onclick=login;
document.getElementById('key').addEventListener('keydown',e=>{if(e.key==='Enter')login()});
document.getElementById('plusBtn').onclick=()=>document.getElementById('plusMenu').classList.toggle('open');
document.getElementById('clearMode').onclick=()=>setMode('chat');
"""
