from __future__ import annotations

PART_5 = r"""function showEmpty(){messages.innerHTML='<div class="empty-state" id="emptyState"><div class="empty-inner"><div class="empty-logo"><svg viewBox="0 0 24 24"><path d="M12 2.8 19.2 7v10L12 21.2 4.8 17V7z"/><path d="m8.2 9.2 3.8-2.1 3.8 2.1v5.6L12 16.9l-3.8-2.1z"/></svg></div><div class="empty-title">How can WorkSpace help?</div><div class="empty-sub">Your chat history stays in the local WorkSpace database.</div></div></div>'}
async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let data={};try{data=await r.json()}catch(e){}if(r.status===401){document.getElementById('login').classList.remove('hidden');throw new Error('Authentication required')}if(!r.ok)throw new Error(data.error||r.statusText);return data}

function applySidebarState(){const side=document.getElementById('sidebar');side.classList.toggle('collapsed',state.sidebarCollapsed);document.body.classList.toggle('sidebar-collapsed',state.sidebarCollapsed);document.getElementById('sidebarToggle').setAttribute('aria-label',state.sidebarCollapsed?'Expand sidebar':'Collapse sidebar')}
function setSidebarCollapsed(value){state.sidebarCollapsed=!!value;localStorage.setItem('workspace.sidebarCollapsed',state.sidebarCollapsed?'1':'0');applySidebarState()}
function toggleSidebar(){setSidebarCollapsed(!state.sidebarCollapsed)}

function appendInline(el,text){const re=/(https?:\/\/[^\s]+)/g;let pos=0;for(const m of String(text||'').matchAll(re)){el.appendChild(document.createTextNode(text.slice(pos,m.index)));const a=document.createElement('a');a.href=m[0];a.target='_blank';a.rel='noopener noreferrer';a.textContent=m[0];a.style.color='var(--accent)';el.appendChild(a);pos=m.index+m[0].length}el.appendChild(document.createTextNode(String(text||'').slice(pos)))}
function renderReport(text){const root=document.createElement('div');root.className='report';let list=null;for(const raw of String(text||'').split('\n')){const line=raw.trimEnd();if(!line.trim()){list=null;continue}if(line==='---'){root.appendChild(document.createElement('hr'));list=null;continue}const h=line.match(/^(#{1,2})\s+(.*)$/);if(h){const el=document.createElement(h[1].length===1?'h1':'h2');appendInline(el,h[2].replace(/\*\*/g,''));root.appendChild(el);list=null;continue}if(line.startsWith('> ')){const q=document.createElement('blockquote');appendInline(q,line.slice(2).replace(/\*\*/g,''));root.appendChild(q);list=null;continue}if(line.startsWith('- ')){if(!list){list=document.createElement('ul');root.appendChild(list)}const li=document.createElement('li');appendInline(li,line.slice(2).replace(/\*\*/g,''));list.appendChild(li);continue}const p=document.createElement('p');appendInline(p,line.replace(/\*\*/g,'').replace(/`/g,''));root.appendChild(p);list=null}return root}
function renderStages(stages){const wrap=document.createElement('div');wrap.className='stages';for(const s of stages||[]){const e=document.createElement('div');e.className='stage '+s.status;const b=document.createElement('b'),small=document.createElement('small');b.textContent=s.label+' · '+s.status;small.textContent=s.detail||'';e.append(b,small);wrap.appendChild(e)}return wrap}
function isPrimary(a){return /_report\.(docx|pdf|md)$/i.test(a.name)||/\.pptx$/i.test(a.name)}
function renderArtifacts(items){const wrap=document.createElement('div'),primary=document.createElement('div'),tech=document.createElement('details');primary.className='downloads';tech.className='tech';const sum=document.createElement('summary');sum.textContent='Technical evidence / 監査用データ';tech.appendChild(sum);let count=0;for(const a of items||[]){const x=document.createElement('a');x.href=a.url;x.textContent='↓ '+a.name;if(isPrimary(a)){if(/_report\.(docx|pdf)$/i.test(a.name))x.className='primaryFile';primary.appendChild(x)}else{tech.appendChild(x);count++}}if(primary.children.length)wrap.appendChild(primary);if(count)wrap.appendChild(tech);return wrap}
async function copyAnswer(node){const text=node.dataset.answer||'';try{await navigator.clipboard.writeText(text)}catch(e){const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}showToast('Copied')}
function renderActions(node,job){if(!job||!job.answer)return;const bar=document.createElement('div');bar.className='answerTools';const b=document.createElement('button');b.textContent='Copy answer';b.onclick=()=>copyAnswer(node);bar.appendChild(b);node.appendChild(bar)}
function addMessage(who,text,cls='',job=null){hideEmpty();const d=document.createElement('div');d.className='msg '+cls;const h=document.createElement('div');h.className='who';h.textContent=who;d.appendChild(h);if(job&&job.stages)d.appendChild(renderStages(job.stages));const b=document.createElement('div');b.className='bubble';if(cls.includes('user'))b.textContent=text;else b.appendChild(renderReport(text));d.appendChild(b);d.dataset.answer=job&&job.answer?job.answer:text;if(job){renderActions(d,job);if(job.artifacts&&job.artifacts.length)d.appendChild(renderArtifacts(job.artifacts))}messages.appendChild(d);messages.scrollTop=messages.scrollHeight;return d}
function updateNode(node,j){const old=node.querySelector('.stages');if(old)old.remove();if(j.stages)node.insertBefore(renderStages(j.stages),node.querySelector('.bubble'));const text=(j.status==='queued'||j.status==='running')?'WorkSpace is working…':(j.answer||(j.error||j.status));const b=node.querySelector('.bubble');b.innerHTML='';b.appendChild(renderReport(text));node.dataset.answer=j.answer||'';for(const e of Array.from(node.querySelectorAll('.answerTools,.downloads,.tech')))e.remove();if(j.answer)renderActions(node,j);if(j.artifacts&&j.artifacts.length)node.appendChild(renderArtifacts(j.artifacts));node.classList.toggle('error',j.status==='failed'&&!j.answer)}

"""
