from __future__ import annotations

PART_2 = r"""#messages{flex:1;overflow:auto;padding:26px 18px 230px;scrollbar-width:thin;scrollbar-color:#34363c transparent}
.empty-state{height:62vh;display:flex;align-items:center;justify-content:center;color:#777a81;text-align:center}
.empty-inner{max-width:440px}.empty-logo{width:50px;height:50px;border-radius:16px;margin:0 auto 14px;display:grid;place-items:center;background:#14161d;border:1px solid #2b2f42;color:#cdd6ff}.empty-logo svg{width:30px;height:30px}.empty-title{color:#cfd1d6;font-weight:600;font-size:18px}.empty-sub{font-size:13px;margin-top:6px}
.msg{max-width:900px;margin:0 auto 24px;word-break:break-word}.who{font-size:12px;color:var(--muted);margin:0 0 6px 4px}.bubble{padding:17px 19px;border:1px solid var(--line);border-radius:18px;background:rgba(24,25,29,.92)}.user .bubble{background:#202226;white-space:pre-wrap;margin-left:auto;max-width:80%}.error .bubble{border-color:#784b50;color:#ffd0d0}
.report h1{font-size:24px;margin:0 0 14px}.report h2{font-size:17px;margin:22px 0 8px}.report p{margin:7px 0}.report ul{padding-left:22px}.report li{margin:5px 0}.report blockquote{margin:10px 0;padding:9px 12px;border-left:3px solid var(--accent);background:#171b27;color:#dce3ff}.report hr{border:0;border-top:1px solid var(--line);margin:20px 0}
.stages{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:10px}.stage{border:1px solid var(--line);border-radius:12px;padding:9px 10px;font-size:12px;background:#111216}.stage b{display:block}.stage small{color:var(--muted)}.stage.completed{border-color:#386249}.stage.running{border-color:#4c5d97}.stage.blocked,.stage.failed{border-color:#75474c}.stage.skipped{opacity:.55}
.answerTools,.downloads{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.answerTools button,.downloads a,.tech a{color:var(--text);text-decoration:none;border:1px solid var(--line);background:#24262b;border-radius:9px;padding:6px 10px;font-size:12px}.downloads a.primaryFile{background:#e8e9ed;color:#111216;border-color:#e8e9ed;font-weight:700}.tech{margin-top:10px;border:1px solid var(--line);border-radius:10px;padding:8px 10px;color:var(--muted)}.tech summary{cursor:pointer}.tech a{display:inline-block;margin:7px 7px 2px 0}

.composer-wrap{position:fixed;left:286px;right:0;bottom:0;padding:48px 18px 22px;background:linear-gradient(transparent,rgba(8,9,11,.94) 24%,var(--bg) 54%);z-index:8;pointer-events:none;transition:left .18s ease}
body.sidebar-collapsed .composer-wrap{left:70px}.composer-area{max-width:940px;margin:auto;position:relative;pointer-events:auto}.disclaimer{text-align:center;color:#74777e;font-size:12px;margin-bottom:11px}.composer{border:1px solid var(--line2);background:rgba(31,32,36,.96);border-radius:32px;box-shadow:0 14px 42px rgba(0,0,0,.28);display:flex;align-items:flex-end;gap:8px;padding:9px 10px;min-height:64px}
.circle-btn{width:46px;height:46px;border:1px solid #44474e;border-radius:50%;background:#242529;display:grid;place-items:center;cursor:pointer;flex:0 0 auto}.circle-btn:hover{background:#2b2d32}.circle-btn svg{width:23px;height:23px}#input{flex:1;border:0;background:transparent;color:var(--text);outline:0;resize:none;min-height:46px;max-height:170px;padding:11px 6px 8px;line-height:1.55}#input::placeholder{color:#a5a7ad}
.composer-actions{display:flex;align-items:center;gap:5px}.effort-select{appearance:none;border:0;background:transparent;color:#d7d8dc;padding:12px 28px 12px 10px;outline:0;cursor:pointer;background-image:linear-gradient(45deg,transparent 50%,#aaa 50%),linear-gradient(135deg,#aaa 50%,transparent 50%);background-position:calc(100% - 14px) 19px,calc(100% - 9px) 19px;background-size:5px 5px,5px 5px;background-repeat:no-repeat}.vline{width:1px;height:32px;background:#383a40;margin:0 3px}#sendBtn{background:var(--accent);border-color:var(--accent);color:#fff}#sendBtn:hover{background:#6c88ff}#sendBtn:disabled{opacity:.45;cursor:not-allowed}#micBtn[aria-disabled="true"]{color:#a6a8ad}
.mode-pill{position:absolute;left:68px;bottom:72px;display:none;align-items:center;gap:8px;border:1px solid #3b4262;background:#1a1d28;border-radius:999px;padding:6px 10px;color:#cfd8ff;font-size:12px}.mode-pill.visible{display:flex}.mode-pill button{border:0;background:transparent;color:#aab8ef;cursor:pointer;padding:0}.attachments{display:flex;gap:7px;flex-wrap:wrap;margin:0 0 9px 10px}.chip{display:flex;align-items:center;gap:6px;max-width:260px;border:1px solid #3a3d45;background:#1c1e22;border-radius:10px;padding:6px 8px;color:#d9dadd;font-size:12px}.chip span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chip button{border:0;background:transparent;color:#8f9299;padding:0 2px;cursor:pointer}

.plus-menu{position:absolute;left:0;bottom:76px;width:min(430px,calc(100vw - 36px));background:rgba(32,33,36,.99);border:1px solid #45474d;border-radius:22px;padding:8px;box-shadow:var(--shadow);display:none;z-index:20;overflow:hidden}.plus-menu.open{display:block}.menu-row{width:100%;border:0;background:transparent;color:var(--text);display:grid;grid-template-columns:42px 1fr auto;gap:8px;align-items:center;text-align:left;padding:11px 12px;border-radius:14px;cursor:pointer}.menu-row:hover{background:#2a2b2f}.menu-row.disabled{opacity:.45;cursor:default}.menu-row.disabled:hover{background:transparent}.menu-icon{width:30px;height:30px;display:grid;place-items:center;color:#8ba0ff}.menu-icon.green{color:#69d7a5}.menu-icon.blue{color:#5cb4ff}.menu-icon.purple{color:#9c83ff}.menu-icon.white{color:#e5e5e7}.menu-icon svg{width:24px;height:24px}.menu-title{font-size:14px}.menu-sub{font-size:12px;color:#a1a4aa}.menu-state{font-size:11px;color:#9fa3ac}.menu-divider{height:1px;background:#3a3c42;margin:5px 10px}.menu-options{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:8px 10px 10px}.menu-options label{font-size:11px;color:#90939a}.menu-options select{width:100%;margin-top:4px;background:#292b30;color:#e7e8ea;border:1px solid #41444c;border-radius:9px;padding:7px}

"""
