from __future__ import annotations

import json
from datetime import datetime
from zoneinfo import ZoneInfo

from .base import BaseAgent
from ..artifacts import ArtifactManager
from ..models import TaskStatus
from ..store import TaskStore

TZ = ZoneInfo("Asia/Tokyo")


class PresentationAgent(BaseAgent):
    agent_id = "presentation"
    profile_file = "agent_presentation.md"

    def run(self, task_id: str, store: TaskStore, artifacts: ArtifactManager, live: bool = False):
        task = store.get_task(task_id)
        research_path = artifacts.root / "research" / artifacts.today() / f"{task_id}.json"
        if not research_path.exists():
            raise FileNotFoundError(f"Research artifact not found: {research_path}")
        research = json.loads(research_path.read_text(encoding="utf-8"))
        store.set_status(task_id, TaskStatus.PRESENTATION_CREATING)
        store.record_activity(task_id, self.agent_id, "presentation_started", "ok", f"live={live}")

        if live:
            content = self.llm.generate(
                self.profile(),
                "Create a professional presentation/report outline based only on this research payload. "
                "Preserve limitations and do not invent facts.\n\n" + json.dumps(research, ensure_ascii=False, indent=2),
            )
            status = "model_generated"
        else:
            content = "Dry-run scaffold only. Presentation content was not generated by an AI model."
            status = "dry_run"

        payload = {
            "task_id": task_id,
            "agent_id": self.agent_id,
            "status": status,
            "source_research_artifact": str(research_path),
            "source_research_status": research.get("status"),
            "content": content,
            "generated_at": datetime.now(TZ).isoformat(),
        }
        markdown = (
            f"# Presentation — {task.title}\n\n**Task:** `{task_id}`  \n"
            f"**Source research:** `{research_path}`  \n**Status:** `{status}`\n\n{content}\n"
        )
        json_path, md_path = artifacts.write_task_artifact("presentations", task_id, payload, markdown)
        store.record_artifact(task_id, self.agent_id, "presentation_json", str(json_path))
        store.record_artifact(task_id, self.agent_id, "presentation_markdown", str(md_path))
        store.set_status(task_id, TaskStatus.PRESENTATION_COMPLETED)
        store.record_activity(task_id, self.agent_id, "presentation_artifact_created", "ok", str(json_path))
        return json_path, md_path
