from __future__ import annotations

import json
from datetime import datetime
from zoneinfo import ZoneInfo

from .base import BaseAgent
from ..artifacts import ArtifactManager
from ..models import TaskStatus
from ..store import TaskStore

TZ = ZoneInfo("Asia/Tokyo")


class ResearchHandoffNotReady(RuntimeError):
    pass


class PresentationAgent(BaseAgent):
    agent_id = "presentation"
    profile_file = "agent_presentation.md"

    def run(self, task_id: str, store: TaskStore, artifacts: ArtifactManager, live: bool = False):
        task = store.get_task(task_id)
        handoff_path = artifacts.research_handoff_path(task_id)
        if not handoff_path.exists():
            raise FileNotFoundError(f"Research handoff not found: {handoff_path}")

        handoff = json.loads(handoff_path.read_text(encoding="utf-8"))
        if handoff.get("presentation_ready") is not True:
            blockers = handoff.get("blockers") or ["UNKNOWN_RESEARCH_BLOCKER"]
            store.set_status(task_id, TaskStatus.WAITING_HUMAN)
            store.record_activity(
                task_id,
                self.agent_id,
                "presentation_blocked_by_research_gate",
                "blocked",
                ",".join(str(item) for item in blockers),
            )
            raise ResearchHandoffNotReady(
                "Research handoff is not presentation-ready; blockers=" + ",".join(str(item) for item in blockers)
            )

        store.set_status(task_id, TaskStatus.PRESENTATION_CREATING)
        store.record_activity(task_id, self.agent_id, "presentation_started", "ok", f"live={live}")

        if live:
            content = self.llm.generate(
                self.profile(),
                "Create a professional presentation/report outline using ONLY this cleaned research handoff. "
                "Do not invent, upgrade confidence, hide conflicts, or alter facts. Preserve source IDs next to factual claims. "
                "Treat inferences as inferences and unresolved items as unresolved.\n\n"
                + json.dumps(handoff, ensure_ascii=False, indent=2),
                think=False,
                num_predict=4096,
            )
            status = "model_generated_from_verified_handoff"
        else:
            content = "Dry-run scaffold only. Presentation content was not generated by an AI model."
            status = "dry_run_from_verified_handoff"

        payload = {
            "task_id": task_id,
            "agent_id": self.agent_id,
            "status": status,
            "source_research_handoff": str(handoff_path),
            "source_research_schema_version": handoff.get("schema_version"),
            "source_quality_metrics": handoff.get("quality_metrics", {}),
            "content": content,
            "generated_at": datetime.now(TZ).isoformat(),
        }
        markdown = (
            f"# Presentation — {task.title}\n\n**Task:** `{task_id}`  \n"
            f"**Source handoff:** `{handoff_path}`  \n**Status:** `{status}`\n\n{content}\n"
        )
        json_path, md_path = artifacts.write_task_artifact("presentations", task_id, payload, markdown)
        store.record_artifact(task_id, self.agent_id, "presentation_json", str(json_path))
        store.record_artifact(task_id, self.agent_id, "presentation_markdown", str(md_path))
        store.set_status(task_id, TaskStatus.PRESENTATION_COMPLETED)
        store.record_activity(task_id, self.agent_id, "presentation_artifact_created", "ok", str(json_path))
        return json_path, md_path
